---
- name: "Download docker-compose"
  get_url:
    url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-{{ ansible_system }}-{{ ansible_machine }}
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Install netstat
  apt:
    name: net-tools
    state: present

- name: Install pip3
  apt:
    name: python3-pip
    state: present


- name: Install docker dep
  pip:
    name: docker

- name: Restart vulnerable environment
  community.docker.docker_container:
    name: log4j
    image: ghcr.io/christophetd/log4shell-vulnerable-app
    state: started
    restart: yes
    ports:
      - "8080:8080"



# - name: Install unzip
#   apt:
#     name: unzip
#     state: latest

# - name: Install java
#   yum:
#     name: java-1.8.0-openjdk
#     state: latest
